keys:
  # PGP User Keys
  - &user_yl_0x8EBD95DC147755A2 8C67A027B7CAC398C88820578EBD95DC147755A2

  # PGP host keys
  - &host_pgp_hades 40F574563C054BDCC05FDF8CC83DFFD75179DF76
  - &host_pgp_hercules 74C749550A06560276DCA8219685DAC2922E7B46
  - &host_pgp_kore 882BE5435E81479DDBFFEF70F5DC39FB0D1A991D
  - &host_pgp_prometheus 42EFF1BA24BF1181C0C4B20329532C0000EE00E4
  - &host_pgp_zeus 99DB0E5347E89C86DBBA763760DAF54F845F5A1D
  - &host_pgp_laptop_server_x86_1 21CC4032C3EA56261C2F096DB7B315CF6141FE6F
  - &host_pgp_laptop_server_x86_2 E9D632250421A9360CEA6185D71690EA67E853C6
  - &host_pgp_laptop_server_x86_3 86D7B916A771B0C9F19025157C5552A043B01BFB

  # Age host keys
  - &host_age_saturn age1uvkcsm082vacmmauxakhuzjyjr7dx7gxyd6k757smwlwm5ekzgzs2sq8uh
creation_rules:
  - path_regex: hosts/nixoses/hades/[^/]+\.sops[^/]*
    key_groups:
      - pgp:
        - *user_yl_0x8EBD95DC147755A2
        - *host_pgp_hades

  - path_regex: hosts/nixoses/hercules/[^/]+\.sops[^/]*
    key_groups:
      - pgp:
        - *user_yl_0x8EBD95DC147755A2
        - *host_pgp_hercules

  - path_regex: hosts/nixoses/kore/[^/]+\.sops[^/]*
    key_groups:
      - pgp:
        - *user_yl_0x8EBD95DC147755A2
        - *host_pgp_kore

  - path_regex: hosts/nixoses/prometheus/[^/]+\.sops[^/]*
    key_groups:
      - pgp:
        - *user_yl_0x8EBD95DC147755A2
        - *host_pgp_prometheus

  - path_regex: hosts/nixoses/laptop-server-x86-1/[^/]+\.sops[^/]*
    key_groups:
      - pgp:
        - *user_yl_0x8EBD95DC147755A2
        - *host_pgp_laptop_server_x86_1

  - path_regex: hosts/nixoses/laptop-server-x86-2/[^/]+\.sops[^/]*
    key_groups:
      - pgp:
        - *user_yl_0x8EBD95DC147755A2
        - *host_pgp_laptop_server_x86_2

  - path_regex: hosts/nixoses/laptop-server-x86-3/[^/]+\.sops[^/]*
    key_groups:
      - pgp:
        - *user_yl_0x8EBD95DC147755A2
        - *host_pgp_laptop_server_x86_3

  - path_regex: hosts/nixoses/zeus/[^/]+\.sops[^/]*
    key_groups:
      - pgp:
        - *user_yl_0x8EBD95DC147755A2
        - *host_pgp_zeus

  - path_regex: hosts/darwins/saturn/[^/]+\.sops[^/]*
    key_groups:
      - pgp:
        - *user_yl_0x8EBD95DC147755A2
        age:
        - *host_age_saturn

  - path_regex: profiles/cluster/laptop/common/[^/]+\.sops[^/]*
    key_groups:
      - pgp:
        - *user_yl_0x8EBD95DC147755A2
        - *host_pgp_laptop_server_x86_1
        - *host_pgp_laptop_server_x86_2
        - *host_pgp_laptop_server_x86_3

  - path_regex: profiles/workstation/darwin/(local|remote)/[^/]+\.sops[^/]*
    key_groups:
      - pgp:
        - *user_yl_0x8EBD95DC147755A2
        age:
        - *host_age_saturn

  - path_regex: profiles/workstation/nixos/(local|remote)/[^/]+\.sops[^/]*
    key_groups:
      - pgp:
        - *user_yl_0x8EBD95DC147755A2
        - *host_pgp_hades
        - *host_pgp_hercules
        - *host_pgp_kore
        - *host_pgp_prometheus
        - *host_pgp_laptop_server_x86_1
        - *host_pgp_laptop_server_x86_2
        - *host_pgp_laptop_server_x86_3
        - *host_pgp_zeus

  - path_regex: profiles/myself/[^/]+\.sops[^/]*
    key_groups:
      - pgp:
        - *user_yl_0x8EBD95DC147755A2
        - *host_pgp_hades
        - *host_pgp_hercules
        - *host_pgp_kore
        - *host_pgp_prometheus
        - *host_pgp_laptop_server_x86_1
        - *host_pgp_laptop_server_x86_2
        - *host_pgp_laptop_server_x86_3
        - *host_pgp_zeus
        age:
        - *host_age_saturn

  - path_regex: modules/.*/[^/]+\.sops[^/]*
    key_groups:
      - pgp:
        - *user_yl_0x8EBD95DC147755A2
        - *host_pgp_hades
        - *host_pgp_hercules
        - *host_pgp_kore
        - *host_pgp_prometheus
        - *host_pgp_laptop_server_x86_1
        - *host_pgp_laptop_server_x86_2
        - *host_pgp_laptop_server_x86_3
        - *host_pgp_zeus
        age:
        - *host_age_saturn
