tap "homebrew/bundle"

cask "alfred"                     # spotlight replacement
cask "charles"                    # Charles Proxy
cask "goland"                     # Goland -- Go IDE
cask "google-chrome"              # my browser of choice
cask "iterm2"                     # my terminal of choice
cask "keybase"                    # Keybase for accessing my encrypted repositories
cask "sequel-pro"                 # MySQL frontend supporting connections through a tunnel
cask "slack"                      # Team communication
cask "tailscale"                  # Tailscale VPN
cask "teamviewer"                 # TeamViewer for remote login
cask "viscosity"                  # VPN Application
cask "vlc"                        # VideoLan video player
cask "whatsapp"                   # WhatsApp application
